# 기초수학과 통계

의료 현장에서 **수학적 사고**는 단순한 계산이 아닙니다. 환자의 생명과 직결된 **논리적 판단**의 도구입니다.

🏥 **의료진의 수학적 사고**
- 환자 상태 변화의 **패턴 인식** (혈압, 체온, 심박수 추이)
- 검사 결과의 **상관관계 분석** (나이-혈압, BMI-당뇨 위험도)
- 치료 효과의 **정량적 평가** (투약 전후 수치 비교)

💡 **목표**: 수학 공식 암기가 아닌, **데이터로 사고하는 방법** 습득

# 1. 스칼라, 벡터, 행렬과 의료 데이터

## 스칼라 (Scalar) - 하나의 숫자

환자의 **개별 정보**를 나타냅니다.

In [ ]:
# 환자 한명의 정보들 (각각이 스칼라)
patient_age = 45        # 나이 (세)
patient_weight = 70.5   # 체중 (kg)
patient_height = 175    # 키 (cm)
patient_bp_high = 120   # 수축기 혈압 (mmHg)
patient_bp_low = 80     # 이완기 혈압 (mmHg)

print("=== 환자 개별 정보 (스칼라) ===")
print(f"나이: {patient_age}세")
print(f"체중: {patient_weight}kg")
print(f"키: {patient_height}cm")
print(f"혈압: {patient_bp_high}/{patient_bp_low}mmHg")

=== 환자 개별 정보 (스칼라) ===
나이: 45세
체중: 70.5kg
키: 175cm
혈압: 120/80mmHg


## 벡터 (Vector) - 한 환자의 모든 정보

환자 **한 명**의 여러 특성을 하나로 묶은 것입니다.

In [ ]:
# 파이썬 리스트로 환자 정보 벡터 만들기
patient_info_list = [45, 70.5, 175, 120, 80]  # [나이, 체중, 키, 수축기BP, 이완기BP]

print("=== 환자의 여러 특성 (벡터) ===")
print(f"환자: {patient_info_list}")

# 각 요소에 접근하기
print(f"\n나이: {patient_info_list[0]}세")
print(f"체중: {patient_info_list[1]}kg")
print(f"키: {patient_info_list[2]}cm")

=== 환자의 여러 특성 (벡터) ===
환자: [45, 70.5, 175, 120, 80]

나이: 45세
체중: 70.5kg
키: 175cm


## 행렬 (Matrix) - 여러 환자의 정보

**여러 환자들**의 정보를 표 형태로 정리한 것입니다.

In [ ]:
# 파이썬 리스트로 환자 데이터베이스 만들기
patients_db_list = [
    [45, 70.5, 175, 120, 80],   # 환자1 (45세, 70.5kg, 175cm, 120/80mmHg)
    [32, 55.0, 162, 110, 75],   # 환자2 (32세, 55kg, 162cm, 110/75mmHg)
    [67, 82.3, 168, 140, 90],   # 환자3 (67세, 82.3kg, 168cm, 140/90mmHg)
    [28, 48.7, 155, 105, 70],   # 환자4 (28세, 48.7kg, 155cm, 105/70mmHg)
]

print("=== 여러 환자의 특성 묶음 (행렬) ===")
print("형태: [나이, 체중, 키, 수축기BP, 이완기BP]")
print()

for i, patient in enumerate(patients_db_list, 1):
    print(f"환자{i}: {patient}")

=== 여러 환자의 특성 묶음 (행렬) ===
형태: [나이, 체중, 키, 수축기BP, 이완기BP]

환자1: [45, 70.5, 175, 120, 80]
환자2: [32, 55.0, 162, 110, 75]
환자3: [67, 82.3, 168, 140, 90]
환자4: [28, 48.7, 155, 105, 70]


### 🤔 실습 문제 1

위 환자 데이터 ```patients_db_list``` 에서 **환자3**의 **체중**을 출력하고, 모든 환자의 **나이**만 출력해보세요.

In [ ]:
# 여기에 작성하세요


In [ ]:
# @title 정답

# 환자3 체중 출력 (박철수는 3번째 환자, 인덱스 2)
# 체중은 두 번째 요소, 인덱스 1
print(f"박철수의 체중: {patients_db_list[2][1]}kg")

print("\n모든 환자의 나이")
for i, patient in enumerate(patients_db_list, 1):
    print(f"환자{i}: {patient[0]}세")

박철수의 체중: 82.3kg

모든 환자의 나이
환자1: 45세
환자2: 32세
환자3: 67세
환자4: 28세


# NumPy란?

NumPy는 AI와 머신러닝의 **핵심 도구**입니다. 의료 현장에서 환자 데이터 분석, 의료 영상 처리, 진단 예측 모델 등을 구현할 때 반드시 사용되는 라이브러리입니다.

파이썬의 기본 리스트로는 수백만 개의 데이터를 빠르게 처리할 수 없지만, NumPy는 **벡터화 연산**을 통해 수천 배 빠른 연산이 가능합니다.

🏥 **의료 현장 예시**: 환자 1만 명의 혈압 데이터 분석
- 파이썬 리스트: 10분 소요
- NumPy 배열: 1초 소요

속도가 생명인 의료 AI에서 NumPy는 필수입니다!

### Numpy 연습 사이트: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [2]:
import numpy as np
print(f"NumPy 버전: {np.__version__}")

NumPy 버전: 2.0.2


# 2. 파이썬 리스트 vs NumPy 배열


같은 작업을 파이썬 리스트와 NumPy로 각각 수행해서 **속도 차이**를 직접 체험해보겠습니다.

**시나리오**: 환자 10,000명의 키를 센티미터에서 미터로 변환

In [ ]:
import time
import random

# 10,000명의 환자 키 데이터 생성 (150-200cm 사이 랜덤)
num_patients = 10000
heights_list = [random.uniform(150, 200) for _ in range(num_patients)]   # 파이썬 리스트
heights_numpy = np.array(heights_list)                                   # Numpy 배열

print(f"환자 수: {num_patients:,}명")
print(f"키 데이터 예시: {heights_list[:5]} (cm)")

환자 수: 10,000명
키 데이터 예시: [165.00928571535496, 183.81451919866728, 171.91159471741952, 153.14770659483196, 175.70322564712697] (cm)


## 방법 1: 파이썬 리스트 + for 반복문

In [ ]:
# 파이썬 리스트로 cm → m 변환
start_time = time.time()

heights_meter_list = []
for height in heights_list: # 10000번 반복
    heights_meter_list.append(height / 100)  # cm를 m로 변환

python_time = time.time() - start_time

print(f"파이썬 리스트 방법: {python_time:.6f}초")
print(f"결과 예시: {heights_meter_list[:5]} (m)")

파이썬 리스트 방법: 0.001579초
결과 예시: [1.6500928571535496, 1.838145191986673, 1.7191159471741952, 1.5314770659483197, 1.7570322564712697] (m)


## 방법 2: NumPy 벡터화 연산

In [ ]:
# NumPy로 cm → m 변환 (벡터화 연산)
start_time = time.time()

heights_meter_numpy = heights_numpy / 100  # 전체 배열을 한 번에 연산!

numpy_time = time.time() - start_time

print(f"NumPy 벡터화 방법: {numpy_time:.6f}초")
print(f"결과 예시: {heights_meter_numpy[:5]} (m)")

NumPy 벡터화 방법: 0.000207초
결과 예시: [1.65009286 1.83814519 1.71911595 1.53147707 1.75703226] (m)


## ⚡ 성능 비교 결과

In [ ]:
speedup = python_time / numpy_time

print("=== 성능 비교 결과 ===")
print(f"파이썬 리스트: {python_time:.6f}초")
print(f"NumPy 배열:    {numpy_time:.6f}초")
print(f"NumPy가 {speedup:.1f}배 더 빠름! 🚀")

# 결과 검증 (두 방법이 같은 결과를 내는지 확인)
# np.allclose(): 두 배열이 "거의 같은지" 확인하는 함수
print(f"\n결과 일치 여부: {np.allclose(heights_meter_list, heights_meter_numpy)}")

=== 성능 비교 결과 ===
파이썬 리스트: 0.001579초
NumPy 배열:    0.000207초
NumPy가 7.6배 더 빠름! 🚀

결과 일치 여부: True


# 3. NumPy 배열 생성하기

AI는 모든 정보를 **숫자 배열**로만 이해합니다. 환자 정보, 의료 영상, 검사 결과 모두 숫자 배열로 변환되어야 AI가 분석할 수 있습니다.

## 환자 데이터를 NumPy 배열로 표현하기

In [ ]:
# 1차원 배열 (벡터): 환자 한 명의 정보
patient_vector = np.array([45, 70.5, 175, 120, 80])
print("=== 1차원 배열 (벡터) ===")
print(f"환자 정보: {patient_vector}")

=== 1차원 배열 (벡터) ===
환자 정보: [ 45.   70.5 175.  120.   80. ]


In [ ]:
# 2차원 배열 (행렬): 여러 환자의 정보

# 형태: [나이, 체중, 키, 수축기BP, 이완기BP]
patients_matrix = np.array([
    [45, 70.5, 175, 120, 80],   # 환자1
    [32, 55.0, 162, 110, 75],   # 환자2
    [67, 82.3, 168, 140, 90],   # 환자3
    [28, 48.7, 155, 105, 70],   # 환자4
])

print("=== 2차원 배열 (행렬) ===")
print(f"환자 데이터베이스:\n{patients_matrix}")

=== 2차원 배열 (행렬) ===
환자 데이터베이스:
[[ 45.   70.5 175.  120.   80. ]
 [ 32.   55.  162.  110.   75. ]
 [ 67.   82.3 168.  140.   90. ]
 [ 28.   48.7 155.  105.   70. ]]


In [ ]:
# 1차원 배열 (벡터): 환자 한 명의 정보
patient_vector = np.array([45, 70.5, 175, 120, 80])

# numpy 배열 타입
print(f"numpy 배열 타입: {type(patient_vector)}") # ndarray


배열 타입: <class 'numpy.ndarray'>
NumPy 배열인지 확인: True

=== dtype 지정 생성 ===
정수형 배열: [ 45  70 175 120  80]
실수형 배열: [ 45.   70.5 175.  120.   80. ]


In [ ]:
# 모든 데이터타입 지정하여 배열 생성
patient_vector_int = np.array([45, 70.5, 175, 120, 80], dtype=int)
patient_vector_float = np.array([45, 70.5, 175, 120, 80], dtype=float)

print(f"\n=== dtype 지정 생성 ===")
print(f"정수형 배열: {patient_vector_int}")
print(f"실수형 배열: {patient_vector_float}")

## 다양한 배열 생성 방법

- `np.zeros(shape)`: 모든 요소가 0인 배열 생성
- `np.ones(shape)`: 모든 요소가 1인 배열 생성  
- `np.arange(start, stop, step)`: 연속된 숫자 배열 생성

In [ ]:
# 영(0)으로 채워진 배열 - 초기 데이터 템플릿 생성
empty_patients = np.zeros((10, 5))  # 10명 환자, 5개 특성
print("=== 빈 환자 데이터 템플릿 ===")
print(f"형태: {empty_patients.shape}")
print(f"내용:\n{empty_patients[:3]}...")  # 처음 3행만 출력


=== 빈 환자 데이터 템플릿 ===
형태: (10, 5)
내용:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]...


In [ ]:
# 1로 채워진 배열 - 기본값 설정
normal_temp = np.ones(100) * 36.5  # 100명의 정상 체온
print(f"=== 정상 체온 배열 ===")
print(f"정상 체온 100개: {normal_temp[:5]}...")  # 처음 5개만 출력


=== 정상 체온 배열 ===
정상 체온 100개: [36.5 36.5 36.5 36.5 36.5]...


In [ ]:
# 연속된 숫자 배열 - 환자 번호, 시간 순서 등
patient_ids = np.arange(1, 101)  # 환자 번호 1~100
print(f"=== 환자 번호 배열 ===")
print(f"환자 ID: {patient_ids[:5]}...{patient_ids[-5:]}")  # 처음과 끝 각 5개씩 출력

=== 환자 번호 배열 ===
환자 ID: [1 2 3 4 5]...[ 96  97  98  99 100]


### 🤔 실습 문제 2

1. 환자 3명의 정보를 담은 2차원 배열을 만들어보세요. (정답 데이터 참고)
2. 50명의 정상 심박수(72bpm)로 채워진 배열을 만들어보세요.

In [ ]:
# 여기에 작성하세요


In [ ]:
# @title 정답

# 1. 환자 3명 데이터 배열
my_patients = np.array([
    [25, 60.0, 170, 115, 75],   # 환자1
    [40, 72.5, 165, 125, 80],   # 환자2
    [55, 68.0, 172, 130, 85]    # 환자3
])

print("=== 나만의 환자 데이터 ===")
print(f"환자 데이터:\n{my_patients}")
print(f"배열 형태: {my_patients.shape}")

# 2. 정상 심박수 배열
normal_heartrate = np.ones(50) * 72
print(f"\n=== 정상 심박수 배열 ===")
print(f"50명의 정상 심박수: {normal_heartrate[:10]}...")  # 처음 10개만
print(f"배열 크기: {normal_heartrate.shape}")

=== 나만의 환자 데이터 ===
환자 데이터:
[[ 25.   60.  170.  115.   75. ]
 [ 40.   72.5 165.  125.   80. ]
 [ 55.   68.  172.  130.   85. ]]
배열 형태: (3, 5)

=== 정상 심박수 배열 ===
50명의 정상 심박수: [72. 72. 72. 72. 72. 72. 72. 72. 72. 72.]...
배열 크기: (50,)


# 4. 배열의 속성과 데이터 추출

## shape, ndim, dtype으로 데이터 구조 파악

데이터를 다루기 전에 **데이터의 구조**를 파악하는 것이 중요합니다.

- `shape`: 배열의 형태 (행, 열 개수) - 환자 수와 특성 개수 확인
- `ndim`: 배열의 차원 수 - 벡터(1차원)인지 행렬(2차원)인지 구분  
- `dtype`: 데이터 타입 - 정수형, 실수형, 문자형 등 확인
- `size`: 전체 요소 개수 - 총 데이터 포인트 수 파악

In [ ]:
# 1차원 배열 (벡터): 환자 한 명의 정보
patient_vector = np.array([45, 70.5, 175, 120, 80])
print("=== 1차원 배열 (벡터) ===")
print(f"환자 정보: {patient_vector}")
print(f"배열 형태: {patient_vector.shape}")
print(f"배열 차원: {patient_vector.ndim}")
print(f"데이터 타입: {patient_vector.dtype}")

=== 1차원 배열 (벡터) ===
환자 정보: [ 45.   70.5 175.  120.   80. ]
배열 형태: (5,)
배열 차원: 1
데이터 타입: float64


In [ ]:
# 2차원 배열 (행렬): 환자데이터
patients_matrix

array([[ 45. ,  70.5, 175. , 120. ,  80. ],
       [ 32. ,  55. , 162. , 110. ,  75. ],
       [ 67. ,  82.3, 168. , 140. ,  90. ],
       [ 28. ,  48.7, 155. , 105. ,  70. ]])

In [ ]:
# 환자 데이터 구조 분석
print("=== 환자 데이터 구조 분석 ===")
print(f"shape (형태): {patients_matrix.shape}")
print(f"  → {patients_matrix.shape[0]}명의 환자, {patients_matrix.shape[1]}개의 특성")

print(f"\nndim (차원): {patients_matrix.ndim}")
print(f"  → {patients_matrix.ndim}차원 배열 (행렬)")

print(f"\ndtype (데이터 타입): {patients_matrix.dtype}")
print(f"  → 실수형 데이터 (소수점 포함 가능)")

print(f"\nsize (총 원소 개수): {patients_matrix.size}")
print(f"  → 총 {patients_matrix.size}개의 숫자")

=== 환자 데이터 구조 분석 ===
shape (형태): (4, 5)
  → 4명의 환자, 5개의 특성

ndim (차원): 2
  → 2차원 배열 (행렬)

dtype (데이터 타입): float64
  → 실수형 데이터 (소수점 포함 가능)

size (총 원소 개수): 20
  → 총 20개의 숫자


## 인덱싱과 슬라이싱으로 필요한 정보 추출

환자별, 특성별로 필요한 데이터만 선별해서 추출할 수 있습니다.

- **인덱싱**: 특정 위치의 하나의 값 추출 (`array[행, 열]`)
- **슬라이싱**: 연속된 여러 값을 범위로 추출 (`array[시작:끝]`)
- **전체 선택**: 콜론(`:`) 사용으로 해당 차원의 모든 데이터 선택

In [4]:
patients_matrix = np.array([
    [45, 70.5, 175, 120, 80],   # 환자1
    [32, 55.0, 162, 110, 75],   # 환자2
    [67, 82.3, 168, 140, 90],   # 환자3
    [28, 48.7, 155, 105, 70],   # 환자4
])

print("=== 여러 환자의 특성 묶음 (행렬) ===")
print("형태: [나이, 체중, 키, 수축기BP, 이완기BP]")
print(f"\n{patients_matrix}")

=== 여러 환자의 특성 묶음 (행렬) ===
형태: [나이, 체중, 키, 수축기BP, 이완기BP]

[[ 45.   70.5 175.  120.   80. ]
 [ 32.   55.  162.  110.   75. ]
 [ 67.   82.3 168.  140.   90. ]
 [ 28.   48.7 155.  105.   70. ]]


### 인덱싱
데이터 한개 추출

In [ ]:
print("=== 특정 환자 정보 추출 ===")
first_patient = patients_matrix[0]  # 첫 번째 환자
last_patient = patients_matrix[-1]  # 마지막 환자

print(f"첫 번째 환자: {first_patient}")
print(f"마지막 환자: {last_patient}")

# 특정 환자의 특정 정보
kim_age = patients_matrix[0, 0]      # 첫 번째 환자의 나이
park_weight = patients_matrix[-1, 1]  # 마지막 환자의 체중

print(f"\n첫 번째 환자의 나이: {kim_age}세")
print(f"마지막 환자의 체중: {park_weight}kg")

=== 특정 환자 정보 추출 ===
첫 번째 환자: [ 45.   70.5 175.  120.   80. ]
마지막 환자: [ 28.   48.7 155.  105.   70. ]

첫 번째 환자의 나이: 45.0세
마지막 환자의 체중: 48.7kg


### 슬라이싱
여러 데이터를 범위로 추출

In [ ]:
# 슬라이싱: 여러 데이터를 한 번에
print("=== 여러 데이터 추출 (슬라이싱) ===")

# 모든 환자의 나이 (첫 번째 열)
all_ages = patients_matrix[:, 0]
print(f"모든 환자의 나이: {all_ages}")

# 모든 환자의 체중 (두 번째 열)
all_weights = patients_matrix[:, 1]
print(f"모든 환자의 체중: {all_weights}")

# 처음 3명 환자의 모든 정보
first_three_patients = patients_matrix[:3, :]
print(f"\n처음 3명 환자:\n{first_three_patients}")

# 모든 환자의 혈압 정보 (마지막 2개 열)
all_blood_pressure = patients_matrix[:, -2:]
print(f"\n모든 환자의 혈압:\n{all_blood_pressure}")


=== 여러 데이터 추출 (슬라이싱) ===
모든 환자의 나이: [45. 32. 67. 28.]
모든 환자의 체중: [70.5 55.  82.3 48.7]

처음 3명 환자:
[[ 45.   70.5 175.  120.   80. ]
 [ 32.   55.  162.  110.   75. ]
 [ 67.   82.3 168.  140.   90. ]]

모든 환자의 혈압:
[[120.  80.]
 [110.  75.]
 [140.  90.]
 [105.  70.]]


## 조건부 인덱싱 (Boolean Indexing)

특정 조건을 만족하는 원소들을 한번에 선택합니다.

- **Boolean 마스크**: 조건 결과로 True/False 배열 생성
  
  `ages >= 50` → `[False, True, True, False, True]`
- **마스크 적용**: True인 위치의 데이터만 추출
  
  `patients[ages >= 50]` → 조건 만족하는 모든 환자 정보


In [5]:
# 조건부 선별: 고혈압 환자 찾기 (수축기 혈압 >= 140)
systolic_bp = patients_matrix[:, 3]  # 수축기 혈압 (4번째 열)
high_bp_mask = systolic_bp >= 130    # 조건 마스크

print("=== 고혈압 환자 찾기 ===")
print(f"모든 환자의 수축기 혈압: {systolic_bp}")
print(f"고혈압 여부 (>=130): {high_bp_mask}")

# 고혈압 환자의 모든 정보
high_bp_patients = patients_matrix[high_bp_mask]
print(f"\n고혈압 환자들:\n{high_bp_patients}")

# 나이 40세 이상 환자들
ages = patients_matrix[:, 0]
elderly_patients = patients_matrix[ages >= 40]
print(f"\n40세 이상 환자들:\n{elderly_patients}")


=== 고혈압 환자 찾기 ===
모든 환자의 수축기 혈압: [120. 110. 140. 105.]
고혈압 여부 (>=130): [False False  True False]

고혈압 환자들:
[[ 67.   82.3 168.  140.   90. ]]

40세 이상 환자들:
[[ 45.   70.5 175.  120.   80. ]
 [ 67.   82.3 168.  140.   90. ]]


### 🤔 실습 문제 3

환자 데이터에서
1. 모든 환자의 키 정보만 추출해보세요
2. 체중이 70kg 이상인 환자들을 찾아보세요

In [ ]:
# 환자 데이터
patients_matrix = np.array([
    [45, 70.5, 175, 120, 80],   # 환자1
    [32, 55.0, 162, 110, 75],   # 환자2
    [67, 82.3, 168, 140, 90],   # 환자3
    [28, 48.7, 155, 105, 70],   # 환자4
])

print("=== 여러 환자의 특성 묶음 (행렬) ===")
print("형태: [나이, 체중, 키, 수축기BP, 이완기BP]")
print(f"\n{patients_matrix}")

=== 여러 환자의 특성 묶음 (행렬) ===
형태: [나이, 체중, 키, 수축기BP, 이완기BP]

[[ 45.   70.5 175.  120.   80. ]
 [ 32.   55.  162.  110.   75. ]
 [ 67.   82.3 168.  140.   90. ]
 [ 28.   48.7 155.  105.   70. ]]


In [ ]:
# 여기에 작성하세요


In [ ]:
# @title 정답

# 1. 모든 환자의 키 (세 번째 열, 인덱스 2)
all_heights = patients_matrix[:, 2]
print("=== 모든 환자의 키 ===")
print(f"키 데이터: {all_heights}cm")

# 2. 체중이 70kg 이상인 환자들
weights = patients_matrix[:, 1]
heavy_patients = patients_matrix[weights > 70]

print(f"\n=== 체중 70kg 이상 환자 ===")
print(f"해당 환자들:\n{heavy_patients}")


=== 모든 환자의 키 ===
키 데이터: [175. 162. 168. 155.]cm

=== 체중 70kg 이상 환자 ===
해당 환자들:
[[ 45.   70.5 175.  120.   80. ]
 [ 67.   82.3 168.  140.   90. ]]


# 5. 벡터화 연산

## for문 없이 배열 전체 연산하기

NumPy의 **벡터화 연산**은 반복문 없이 전체 배열에 대해 연산을 수행합니다. 이는 의료 데이터 처리에서 매우 중요한 기능입니다.

## 벡터 연산: 모든 환자 키를 미터로 변환

In [ ]:
# for문으로 했다면?
heights_m_manual = []
for height in patients_matrix[:, 2]:
    heights_m_manual.append(height / 100)

print(f"변환 결과: {np.array(heights_m_manual)}")

변환 결과: [1.75 1.62 1.68 1.55]


In [ ]:
# 환자들의 키 데이터 (cm)
heights_cm = patients_matrix[:, 2]
print("=== 키 단위 변환 (cm → m) ===")
print(f"원본 키 (cm): {heights_cm}")

# 벡터화 연산: 전체 배열을 한 번에 나누기
heights_m = heights_cm / 100
print(f"변환된 키 (m): {heights_m}")


=== 키 단위 변환 (cm → m) ===
원본 키 (cm): [175. 162. 168. 155.]
변환된 키 (m): [1.75 1.62 1.68 1.55]


### 🤔 실습 문제 4

1. 모든 환자의 나이에 1을 더해서 "내년 나이"를 계산해보세요
2. 체중(kg)을 파운드(lb)로 변환해보세요 (1kg = 2.205lb)

In [ ]:
# 환자 데이터
patients_matrix = np.array([
    [45, 70.5, 175, 120, 80],   # 환자1
    [32, 55.0, 162, 110, 75],   # 환자2
    [67, 82.3, 168, 140, 90],   # 환자3
    [28, 48.7, 155, 105, 70],   # 환자4
])

print("=== 여러 환자의 특성 묶음 (행렬) ===")
print("형태: [나이, 체중, 키, 수축기BP, 이완기BP]")
print(f"\n{patients_matrix}")

=== 여러 환자의 특성 묶음 (행렬) ===
형태: [나이, 체중, 키, 수축기BP, 이완기BP]

[[ 45.   70.5 175.  120.   80. ]
 [ 32.   55.  162.  110.   75. ]
 [ 67.   82.3 168.  140.   90. ]
 [ 28.   48.7 155.  105.   70. ]]


In [ ]:
# 여기에 작성하세요


In [ ]:
# @title 정답

# 1. 내년 나이 계산
current_ages = patients_matrix[:, 0]
next_year_ages = current_ages + 1

print("=== 내년 나이 계산 ===")
print(f"현재 나이: {current_ages}")
print(f"내년 나이: {next_year_ages}")

# 2. 체중을 파운드로 변환
weights_kg = patients_matrix[:, 1]
weights_lb = weights_kg * 2.205

print(f"\n=== 체중 단위 변환 ===")
print(f"체중 (kg): {weights_kg}")
print(f"체중 (lb): {np.round(weights_lb, 2)}")


=== 내년 나이 계산 ===
현재 나이: [45. 32. 67. 28.]
내년 나이: [46. 33. 68. 29.]

=== 체중 단위 변환 ===
체중 (kg): [70.5 55.  82.3 48.7]
체중 (lb): [155.45 121.28 181.47 107.38]


# 6. 기초 통계 함수

## 의료 데이터 분석의 핵심: 환자군 통계 분석

**기초 통계 함수**는 의료진이 환자군의 특성을 파악하고 임상 결정을 내리는 데 필수적인 도구입니다.   
환자들의 생체 지표에서 최솟값, 최댓값, 평균값을 찾아 정상 범위를 설정하고 이상 케이스를 식별합니다.



In [ ]:
# 10명 환자의 수축기 혈압 데이터 (mmHg)
blood_pressure = np.array([120, 135, 118, 142, 128, 156, 110, 139, 125, 148])

print("=== 환자 혈압 기본 통계 ===")
print(f"환자 혈압 데이터: {blood_pressure}")
print(f"환자 수: {len(blood_pressure)}명")



=== 환자 혈압 기본 통계 ===
환자 혈압 데이터: [120 135 118 142 128 156 110 139 125 148]
환자 수: 10명


## 기본 통계 함수


In [ ]:
# 기본 통계 함수들
min_bp = np.min(blood_pressure)         # 최솟값
max_bp = np.max(blood_pressure)         # 최댓값
mean_bp = np.mean(blood_pressure)       # 평균값
std_bp = np.std(blood_pressure)         # 표준편차

print(f"\n📊 혈압 분석 결과:")
print(f"최저 혈압: {min_bp} mmHg")
print(f"최고 혈압: {max_bp} mmHg")
print(f"평균 혈압: {mean_bp:.1f} mmHg")
print(f"표준편차: {std_bp:.1f} mmHg")

# 분석 결과 분류
if min_bp < 90:
    print(f"\n⚠️  저혈압 환자 발견: {min_bp} mmHg")
else:
    print(f"\n✅ 저혈압 환자 없음 (최저: {min_bp} mmHg)")

if max_bp >= 140:
    print(f"\n⚠️  고혈압 환자 발견: {max_bp} mmHg")
else:
    print(f"\n✅ 고혈압 환자 없음 (최고: {max_bp} mmHg)")




📊 혈압 분석 결과:
최저 혈압: 110 mmHg
최고 혈압: 156 mmHg
평균 혈압: 132.1 mmHg
표준편차: 13.7 mmHg

✅ 저혈압 환자 없음 (최저: 110 mmHg)

⚠️  고혈압 환자 발견: 156 mmHg


## argmin과 argmax


argmin과 argmax는 값이 아니라 **위치(인덱스)를** 찾아주는 함수입니다.  
의료 데이터에서 "어떤 환자가 가장 높은/낮은 수치를 가지고 있는지"를 빠르게 식별할 때 매우 유용합니다.

- **argmin**: 배열에서 최솟값이 위치한 인덱스 반환
- **argmax**: 배열에서 최댓값이 위치한 인덱스 반환  


In [ ]:
## argmin과 argmax: 극값 환자 찾기

# 극값의 위치(인덱스) 찾기
min_index = np.argmin(blood_pressure)    # 최솟값 위치
max_index = np.argmax(blood_pressure)    # 최댓값 위치

print("=== 극값 환자 식별 ===")
print(f"최저 혈압 환자: {min_index+1}번째 환자 ({blood_pressure[min_index]} mmHg)")
print(f"최고 혈압 환자: {max_index+1}번째 환자 ({blood_pressure[max_index]} mmHg)")

# 환자 ID와 연결
patient_ids = np.array(['P001', 'P002', 'P003', 'P004', 'P005',
                       'P006', 'P007', 'P008', 'P009', 'P010'])

print(f"\n👤 환자 식별:")
print(f"최저 혈압: {patient_ids[min_index]} 환자 ({blood_pressure[min_index]} mmHg)")
print(f"최고 혈압: {patient_ids[max_index]} 환자 ({blood_pressure[max_index]} mmHg)")

print(f"\n📋 특별 관리 대상:")
print(f"• {patient_ids[min_index]} 환자: 저혈압 모니터링 필요")
print(f"• {patient_ids[max_index]} 환자: 고혈압 치료 우선순위")


=== 극값 환자 식별 ===
최저 혈압 환자: 7번째 환자 (110 mmHg)
최고 혈압 환자: 6번째 환자 (156 mmHg)

👤 환자 식별:
최저 혈압: P007 환자 (110 mmHg)
최고 혈압: P006 환자 (156 mmHg)

📋 특별 관리 대상:
• P007 환자: 저혈압 모니터링 필요
• P006 환자: 고혈압 치료 우선순위


## 축(axis) 개념

axis는 다차원 배열에서 "어느 방향으로 연산을 수행할지"를 지정하는 파라미터입니다.

- **axis=0**: 세로 방향 → 열별 통계 (각 생체지표별 전체 환자 평균)
- **axis=1**: 가로 방향 → 행별 통계 (각 환자별 모든 지표 평균)
- **의미**: axis=0은 "환자군 현황 파악", axis=1은 "개별 환자 종합 평가"

In [ ]:
## 다차원 배열에서의 통계

# 여러 환자의 다양한 생체 지표
# 행: 환자, 열: [나이, 수축기혈압, 혈당]
patients_data = np.array([
    [45, 120, 95],    # 환자1
    [67, 156, 180],   # 환자2
    [32, 110, 88],    # 환자3
    [58, 142, 102],   # 환자4
    [29, 118, 92]     # 환자5
])

features = ['나이', '수축기혈압', '혈당']


In [ ]:
print("=== 다차원 의료 데이터 분석 ===")
print(f"환자 데이터 (5명 × 3지표):")
print(f"{'환자':<5} {'나이':<5} {'혈압':<8} {'혈당':<5}")
print("-" * 25)
for i, data in enumerate(patients_data, 1):
    print(f"P{i:03d}  {data[0]:<5} {data[1]:<8} {data[2]:<5}")

# axis=0: 열 방향 (환자들을 비교) → 각 지표별 통계
# axis=1: 행 방향 (지표들을 비교) → 각 환자별 통계

print(f"\n📊 지표별(열방향) 통계 (axis=0):")
min_by_feature = np.min(patients_data, axis=0)   # ndarray
max_by_feature = np.max(patients_data, axis=0)   # ndarray
mean_by_feature = np.mean(patients_data, axis=0) # ndarray

for i, feature in enumerate(features):
    print(f"{feature}: 최소 {min_by_feature[i]:.0f}, 최대 {max_by_feature[i]:.0f}, 평균 {mean_by_feature[i]:.1f}")

print(f"\n👥 환자별(행방향) 평균 점수 (axis=1):")
patient_means = np.mean(patients_data, axis=1)
for i, mean_score in enumerate(patient_means, 1):
    print(f"환자 P{i:03d}: {mean_score:.1f}")



=== 다차원 의료 데이터 분석 ===
환자 데이터 (5명 × 3지표):
환자    나이    혈압       혈당   
-------------------------
P001  45    120      95   
P002  67    156      180  
P003  32    110      88   
P004  58    142      102  
P005  29    118      92   

📊 지표별(열방향) 통계 (axis=0):
나이: 최소 29, 최대 67, 평균 46.2
수축기혈압: 최소 110, 최대 156, 평균 129.2
혈당: 최소 88, 최대 180, 평균 111.4

👥 환자별(행방향) 평균 점수 (axis=1):
환자 P001: 86.7
환자 P002: 134.3
환자 P003: 76.7
환자 P004: 100.7
환자 P005: 79.7


### 🤔 실습 문제 5

병원 응급실 환자들의 체온 데이터를 분석해보세요.
1. 기본 통계 계산: 최솟값, 최댓값, 평균, 표준편차
2. 극값 환자 찾기: 가장 높은/낮은 체온 환자의 위치

In [ ]:
# 응급실 환자 체온 데이터 (섭씨)
body_temps = np.array([36.2, 37.8, 39.1, 36.5, 38.9, 37.2, 40.2, 36.8,
                      39.5, 37.1, 38.3, 36.9, 39.8, 37.4, 38.1])

print("=== 응급실 환자 체온 분석 ===")
print(f"환자 체온 데이터: {body_temps}")

# 여기에 작성하세요

In [ ]:
# @title 정답

# 응급실 환자 체온 데이터 (섭씨)
body_temps = np.array([36.2, 37.8, 39.1, 36.5, 38.9, 37.2, 40.2, 36.8,
                      39.5, 37.1, 38.3, 36.9, 39.8, 37.4, 38.1])

print("=== 응급실 환자 체온 분석 ===")
print(f"환자 체온 데이터: {body_temps}")

# 1. 기본 통계 계산
min_temp = np.min(body_temps)
max_temp = np.max(body_temps)
mean_temp = np.mean(body_temps)
std_temp = np.std(body_temps)

print(f"\n📊 체온 기본 통계:")
print(f"최저 체온: {min_temp:.1f}°C")
print(f"최고 체온: {max_temp:.1f}°C")
print(f"평균 체온: {mean_temp:.1f}°C")
print(f"표준편차: {std_temp:.1f}°C")

# 2. 극값 환자 위치 찾기
min_temp_index = np.argmin(body_temps)
max_temp_index = np.argmax(body_temps)

print(f"\n👤 극값 환자 식별:")
print(f"최저 체온 환자: {min_temp_index+1}번째 ({body_temps[min_temp_index]:.1f}°C)")
print(f"최고 체온 환자: {max_temp_index+1}번째 ({body_temps[max_temp_index]:.1f}°C)")

=== 응급실 환자 체온 분석 ===
환자 체온 데이터: [36.2 37.8 39.1 36.5 38.9 37.2 40.2 36.8 39.5 37.1 38.3 36.9 39.8 37.4
 38.1]

📊 체온 기본 통계:
최저 체온: 36.2°C
최고 체온: 40.2°C
평균 체온: 38.0°C
표준편차: 1.2°C

👤 극값 환자 식별:
최저 체온 환자: 1번째 (36.2°C)
최고 체온 환자: 7번째 (40.2°C)


# 7. 내적과 행렬곱

## AI 예측의 핵심: 환자 정보 × 가중치 벡터

**내적(Dot Product)**은 AI가 예측을 만드는 핵심 연산입니다. 환자의 정보와 AI가 학습한 가중치를 곱해서 예측값을 계산합니다.

## 두 벡터의 내적(dot product)

In [ ]:
# 간단한 내적 예시
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

print("=== 내적 기본 개념 ===")
print(f"벡터 A: {vector_a}")
print(f"벡터 B: {vector_b}")

# 내적 계산: 대응 원소끼리 곱해서 모두 더하기
dot_manual = vector_a[0] * vector_b[0] + vector_a[1] * vector_b[1] + vector_a[2] * vector_b[2]

print(f"\n수동 계산: {vector_a[0]}×{vector_b[0]} + {vector_a[1]}×{vector_b[1]} + {vector_a[2]}×{vector_b[2]} = {dot_manual}")


=== 내적 기본 개념 ===
벡터 A: [1 2 3]
벡터 B: [4 5 6]

수동 계산: 1×4 + 2×5 + 3×6 = 32


In [ ]:
# NumPy에서 내적 계산하는 3가지 방법
dot_numpy = np.dot(vector_a, vector_b)      # 1. np.dot() 함수 - 가장 기본적
dot_operator = vector_a @ vector_b          # 2. @ 연산자 (Python 3.5+) - 최신 트렌트
dot_method = vector_a.dot(vector_b)         # 3. .dot() 메소드 - 비추천

print(f"np.dot(): {dot_numpy}")
print(f"@ 연산자: {dot_operator}")
print(f".dot() 메소드: {dot_method}")

np.dot(): 32
@ 연산자: 32
.dot() 메소드: 32


## 의료 예측 시뮬레이션: 당뇨병 위험도 예측

In [ ]:
# 당뇨병 위험도 예측 시나리오
# 환자 정보: [나이, 체중, BMI]
# AI가 학습한 가중치 (가상의 값)

patient_info = np.array([45, 85, 25])  # 환자 데이터
weights = np.array([0.02, 0.015, 0.08])  # 학습된 가중치

print("=== 당뇨병 위험도 예측 ===")
print(f"환자 데이터: {patient_info}")
print(f"학습된 가중치: {weights}")

# 내적으로 위험도 점수 계산
risk_score = np.dot(patient_info, weights)

print(f"\n=== 내적 계산 ===")
print(f"45 × 0.02 + 85 × 0.015 + 25 × 0.08")
print(f"= 0.9 + 1.275 + 2.0")
print(f"= {risk_score:.3f} (위험도 점수)")

# 위험도 해석
if risk_score < 2.0:
    risk_level = "낮음"
elif risk_score < 4.0:
    risk_level = "보통"
elif risk_score < 6.0:
    risk_level = "높음"
else:
    risk_level = "매우 높음"

print(f"\n📊 당뇨병 위험도: {risk_level}")

=== 당뇨병 위험도 예측 ===
환자 데이터: [45 85 25]
학습된 가중치: [0.02  0.015 0.08 ]

=== 내적 계산 ===
45 × 0.02 + 85 × 0.015 + 25 × 0.08
= 0.9 + 1.275 + 2.0
= 4.175 (위험도 점수)

📊 당뇨병 위험도: 높음


## 여러 환자 동시 예측: 행렬곱 활용

In [ ]:
# 여러 환자 데이터를 3개 특성으로 구성 (나이, 체중, BMI)
patients_data = np.array([
    [45, 85, 25],   # 환자1
    [32, 60, 22],   # 환자2
    [67, 90, 28],   # 환자3
])

print("=== 전체 환자 당뇨병 위험도 예측 ===")
print(f"환자 데이터 (3명 × 3특성):\n{patients_data}")
print(f"가중치 벡터: {weights}")

# 환자의 위험도 수동 계산
risk_scores_method = []
for i in range(len(patients_data)):
    # 각 환자의 가중합 계산
    risk_score = (patients_data[i, 0] * weights[0] +
                  patients_data[i, 1] * weights[1] +
                  patients_data[i, 2] * weights[2])
    risk_scores_method.append(risk_score)
    print(f"환자 {i+1}: {patients_data[i, 0]} × {weights[0]} + {patients_data[i, 1]} × {weights[1]} + {patients_data[i, 2]} × {weights[2]} = {risk_score}")


print(f"\n=== 수동 계산 예측 결과 ===")
print(f"결과: {np.round(risk_scores_method, 3)}")




=== 전체 환자 당뇨병 위험도 예측 ===
환자 데이터 (3명 × 3특성):
[[45 85 25]
 [32 60 22]
 [67 90 28]]
가중치 벡터: [0.02  0.015 0.08 ]
환자 1: 45 × 0.02 + 85 × 0.015 + 25 × 0.08 = 4.175
환자 2: 32 × 0.02 + 60 × 0.015 + 22 × 0.08 = 3.3
환자 3: 67 × 0.02 + 90 × 0.015 + 28 × 0.08 = 4.93

=== 수동 계산 예측 결과 ===
결과: [4.175 3.3   4.93 ]


In [ ]:
# 행렬곱으로 모든 환자의 위험도 한 번에 계산
all_risk_scores = np.dot(patients_data, weights)

print(f"\n=== 예측 결과 ===")
print(f"위험도 점수들: {np.round(all_risk_scores, 3)}")

print(f"\n=== 환자별 위험도 분석 ===")
for i, score in enumerate(all_risk_scores, 1):
    if score < 2.0:
        risk_level = "낮음"
        emoji = "💚"
    elif score < 4.0:
        risk_level = "보통"
        emoji = "💛"
    elif score < 6.0:
        risk_level = "높음"
        emoji = "🧡"
    else:
        risk_level = "매우 높음"
        emoji = "❤️"

    print(f"{emoji} 환자{i}: {score:.3f} ({risk_level})")



=== 예측 결과 ===
위험도 점수들: [4.175 3.3   4.93 ]

=== 환자별 위험도 분석 ===
🧡 환자1: 4.175 (높음)
💛 환자2: 3.300 (보통)
🧡 환자3: 4.930 (높음)


## 행렬 전치(Transpose)

행과 열의 위치를 서로 바꾸는 연산입니다.

- **위치 변환**: (행, 열) → (열, 행)으로 좌표가 바뀜
  - 원본 `[0, 1]` 위치 → 전치 후 `[1, 0]` 위치
  - 원본 `[2, 0]` 위치 → 전치 후 `[0, 2]` 위치
- **형태 변환**: (m×n) 행렬 → (n×m) 행렬로 변환
  - 예: (3×4) → (4×3), (5×2) → (2×5)
- **사용 목적**: 행렬곱에서 shape 맞추기, 데이터 구조 변경 (환자별 -> 특성별)
- **표기법**: `array.T` 또는 `np.transpose(array)`

In [ ]:
# 행렬 전치: Shape 맞추기를 위한 활용
print("=== 행렬곱을 위한 전치 활용 ===")

# 환자 데이터: 2명, 3개 특성 (나이, 체중, BMI)
patients_data = np.array([
    [45, 70, 25],  # 환자1
    [32, 55, 22]   # 환자2
])

# 가중치: 2개 값 (환자별 가중치)
weights = np.array([0.8, 1.2])

print(f"환자 데이터 shape: {patients_data.shape}")  # (2, 3)
print(f"가중치 shape: {weights.shape}")             # (2,)


=== 행렬곱을 위한 전치 활용 ===
환자 데이터 shape: (2, 3)
가중치 shape: (2,)


In [ ]:
# ❌ (2×3) × (2,) → 불가능 (열 개수 ≠ 행 개수)

result = np.dot(patients_data, weights)

ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:

# 전치하여 행열 위치 변경
patients_transposed = patients_data.T

print(f"기존 환자 데이터:\n {patients_data}")
print(f"\n전치된 환자 데이터:\n {patients_transposed} \n")

print("=" * 30)

print(f"\n기존 환자 데이터 shape: {patients_data.shape}")
print(f"\n전치된 환자 데이터 shape: {patients_transposed.shape}")


기존 환자 데이터:
 [[45 70 25]
 [32 55 22]]

전치된 환자 데이터:
 [[45 32]
 [70 55]
 [25 22]] 


기존 환자 데이터 shape: (2, 3)

전치된 환자 데이터 shape: (3, 2)


In [ ]:
# ✅ (3×2) × (2,) → (3,) 가능 (열 개수 == 행 개수)
result = np.dot(patients_transposed, weights)
print(f"결과: {result}")
print(f"→ 각 특성별 가중 합계: 나이={result[0]:.1f}, 체중={result[1]:.1f}, BMI={result[2]:.1f}")

결과: [ 74.4 122.   46.4]
→ 각 특성별 가중 합계: 나이=74.4, 체중=122.0, BMI=46.4


### 🤔 실습 문제 6

심혈관 질환 위험도 예측을 해보세요.
1. 새로운 가중치 벡터를 만들어보세요: `[0.03, 0.01, 0.08]`
2. 모든 환자의 심혈관 위험도를 계산해보세요

In [ ]:
# 환자 데이터
patients_data = np.array([
    [45, 85, 25],   # 환자1
    [32, 60, 22],   # 환자2
    [67, 90, 28],   # 환자3
])

In [ ]:
# 여기에 작성하세요


In [ ]:
# @title 정답

# 1. 심혈관 질환 가중치 (3개 특성용)
cardiovascular_weights = np.array([0.03, 0.01, 0.08])

print("=== 심혈관 질환 위험도 예측 ===")
print(f"심혈관 가중치: {cardiovascular_weights}")

# 2. 모든 환자의 심혈관 위험도 계산
cardio_risk_scores = np.dot(patients_data, cardiovascular_weights)

print(f"\n=== 심혈관 위험도 결과 ===")
for index, score in enumerate(cardio_risk_scores, 1):
    print(f"환자{index}: {score:.3f}")


=== 심혈관 질환 위험도 예측 ===
심혈관 가중치: [0.03 0.01 0.08]

=== 심혈관 위험도 결과 ===
환자1: 4.200
환자2: 3.320
환자3: 5.150
